#pragma once

//From glfw3.h
#define CROC_MOUSE_BUTTON_1         0
#define CROC_MOUSE_BUTTON_2         1
#define CROC_MOUSE_BUTTON_3         2
#define CROC_MOUSE_BUTTON_4         3
#define CROC_MOUSE_BUTTON_5         4
#define CROC_MOUSE_BUTTON_6         5
#define CROC_MOUSE_BUTTON_7         6
#define CROC_MOUSE_BUTTON_8         7
#define CROC_MOUSE_BUTTON_LAST      CROC_MOUSE_BUTTON_8
#define CROC_MOUSE_BUTTON_LEFT      CROC_MOUSE_BUTTON_1
#define CROC_MOUSE_BUTTON_RIGHT     CROC_MOUSE_BUTTON_2
#define CROC_MOUSE_BUTTON_MIDDLE    CROC_MOUSE_BUTTON_3